version: '3'

services:

    app:
        # image: php:fpm-alpine
        build:
            context: .
            dockerfile: Dockerfile.app
        container_name: app
        networks:
            - app-network
        volumes:
            - .:/var/www/public:ro
        working_dir: /var/www/public

    webserver:
        image: nginx:alpine
        container_name: webserver
        networks:
            - app-network
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - .:/var/www/public:ro
            - ./webserver.conf:/etc/nginx/conf.d/default.conf:ro
        working_dir: /var/www/public

    db:
        image: mariadb:10
        container_name: db
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        networks:
            - app-network
        ports:
            - "3306:3306"

    phpmyadmin:
        image: phpmyadmin:latest
        container_name: pma
        environment:
            PMA_ARBITRARY: 1
        networks:
            - app-network
        ports:
            - "8080:80"

networks:
    app-network:
        driver: bridge
